import type { ActionRecord } from "@halo/runtime/contracts";
import type { SystemActionInput, SystemActionOutcome, SystemActionProvider } from "@halo/runtime/system-actions";
import type { LanguagePack } from "@halo/language/language-pack";
import { normalizeForMatching } from "@halo/language/normalize";
import { parseNumber } from "@halo/language/parsers/numerals";

/**
 * HALO Phase 4 — deterministic appointment offering and booking (plan §P8.10).
 *
 * The conversation never books anything: this provider does, through the
 * tenant's existing scheduling engine, and only then may the reply say so
 * (the runtime's validator enforces that). Slots are generated by the
 * engine — the model never invents a time — selection is matched
 * deterministically (ordinals, digits or a time expression), and every
 * booking carries an idempotency key so a repeated "yes" cannot double-book.
 *
 * The port is intentionally minimal so this package stays independent of the
 * scheduling implementation; the application adapts it to `BookingService`,
 * whose `EXCLUDE USING gist` constraint remains the double-booking arbiter.
 */

export interface VisitSlot {
  startsAt: string;
  endsAt: string;
  staffId: string;
  /** Spoken label in the tenant's timezone and language, built by the adapter. */
  label: string;
}

export type VisitBookingResult =
  | { ok: true; appointmentId: string; startsAt: string; label: string }
  | { ok: false; reason: "slot_taken"; alternatives: VisitSlot[] }
  | { ok: false; reason: "invalid"; message: string }
  | { ok: false; reason: "unavailable"; message: string };

export interface VisitBookingPort {
  /** Slots from the scheduling engine. `gloss` is an English time hint, if any. */
  offerSlots(params: { gloss: string | null; now: Date; limit: number }): Promise<VisitSlot[]>;
  book(params: {
    slot: VisitSlot;
    name: string;
    phone: string;
    notes: string;
    idempotencyKey: string;
    now: Date;
  }): Promise<VisitBookingResult>;
}

export interface BookingStepState {
  phase: "idle" | "offered" | "booked" | "failed";
  offered: VisitSlot[];
  appointmentId: string | null;
  bookedLabel: string | null;
  attempts: number;
}

export function emptyBookingState(): BookingStepState {
  return { phase: "idle", offered: [], appointmentId: null, bookedLabel: null, attempts: 0 };
}

export interface BookingStepDeps {
  booking: VisitBookingPort;
  pack: LanguagePack;
  /** Runs only when this returns true (e.g. qualification complete and the caller agreed). */
  isReady: () => boolean;
  /** Contact details for the booking, from qualification and the call itself. */
  contact: () => { name: string; phone: string; notes: string };
  /** Stable per-conversation key prefix for idempotency. */
  conversationId: string;
  maxOffers?: number;
  maxAttempts?: number;
  onBooked?: (appointmentId: string) => void;
}

const ORDINALS: Array<{ index: number; words: string[] }> = [
  { index: 0, words: ["మొదటి", "మొదటిది", "మొదటిదాన్ని", "modati", "modatidi", "first", "one", "1"] },
  { index: 1, words: ["రెండవ", "రెండోది", "రెండో", "rendo", "rendava", "second", "two", "2"] },
  { index: 2, words: ["మూడవ", "మూడోది", "మూడో", "moodo", "moodava", "third", "three", "3"] },
];

export class VisitBookingStepProvider implements SystemActionProvider {
  readonly name = "site_visit_booking";
  private state: BookingStepState = emptyBookingState();

  constructor(private readonly deps: BookingStepDeps) {}

  current(): BookingStepState {
    return this.state;
  }

  async prepare(input: SystemActionInput): Promise<SystemActionOutcome | null> {
    if (this.state.phase === "booked") {
      return {
        sections: [
          `Appointment (verified): the site visit is booked for ${this.state.bookedLabel}. ` +
            `You may confirm this to the caller. Do not offer another time unless they ask to change it.`,
        ],
        actions: [],
      };
    }
    if (!this.deps.isReady()) return null;

    const maxAttempts = this.deps.maxAttempts ?? 3;
    if (this.state.attempts >= maxAttempts) return null;

    // 1. Nothing offered yet: ask the engine for real slots.
    if (this.state.phase === "idle" || this.state.offered.length === 0) {
      return this.offer(input, null);
    }

    // 2. Slots are on the table: did the caller pick one?
    const choice = this.matchChoice(input.userMessage, this.state.offered);
    if (!choice) {
      const gloss = this.deps.pack.hasTime(input.userMessage) ? this.deps.pack.timeGloss(input.userMessage) : null;
      if (gloss) return this.offer(input, gloss);
      this.state.attempts += 1;
      return {
        sections: [
          `Appointment (system): the caller has not chosen a time yet. Offer exactly these, once more, and ask them to pick one: ` +
            `${this.state.offered.map((s, i) => `${i + 1}) ${s.label}`).join(", ")}. Do not invent any other time.`,
        ],
        actions: [],
      };
    }

    // 3. Act first: book it, then let the reply narrate what happened.
    const contact = this.deps.contact();
    const result = await this.deps.booking.book({
      slot: choice,
      name: contact.name,
      phone: contact.phone,
      notes: contact.notes,
      // Same conversation + same slot = the same booking, however often the
      // caller says yes.
      idempotencyKey: `${this.deps.conversationId}:${choice.startsAt}`,
      now: input.now,
    });

    if (result.ok) {
      this.state = { ...this.state, phase: "booked", appointmentId: result.appointmentId, bookedLabel: result.label };
      this.deps.onBooked?.(result.appointmentId);
      const action: ActionRecord = {
        source: "system",
        name: "appointment.book",
        status: "succeeded",
        claimsPermitted: ["appointment.book"],
        summary: `Site visit booked for ${result.label}.`,
      };
      return {
        sections: [
          `Appointment (verified): the site visit IS booked for ${result.label}. Confirm that to the caller, briefly, ` +
            `and tell them they will get a confirmation message.`,
        ],
        actions: [action],
        statePatch: { slots: { appointment_time: result.label.slice(0, 240) } },
      };
    }

    this.state.attempts += 1;
    if (result.reason === "slot_taken") {
      this.state = { ...this.state, phase: "offered", offered: result.alternatives };
      return {
        sections: [
          `Appointment (system): that time was just taken, so NOTHING is booked. Say so plainly and offer exactly these ` +
            `instead: ${result.alternatives.map((s, i) => `${i + 1}) ${s.label}`).join(", ")}.`,
        ],
        actions: [
          { source: "system", name: "appointment.book", status: "failed", claimsPermitted: [], summary: "The chosen slot was taken." },
        ],
      };
    }

    this.state = { ...this.state, phase: "failed" };
    return {
      sections: [
        `Appointment (system): the booking could not be completed (${result.message}). NOTHING is booked — do not say it is. ` +
          `Tell the caller the team will call back to fix a time.`,
      ],
      actions: [
        {
          source: "system",
          name: "appointment.book",
          status: "failed",
          claimsPermitted: [],
          summary: `Booking failed: ${result.message}`,
          needsHuman: true,
        },
      ],
    };
  }

  private async offer(input: SystemActionInput, gloss: string | null): Promise<SystemActionOutcome | null> {
    const hint = gloss ?? (this.deps.pack.hasTime(input.userMessage) ? this.deps.pack.timeGloss(input.userMessage) : null);
    const slots = await this.deps.booking.offerSlots({ gloss: hint, now: input.now, limit: this.deps.maxOffers ?? 3 });
    if (slots.length === 0) {
      this.state = { ...this.state, phase: "failed", attempts: this.state.attempts + 1 };
      return {
        sections: [
          "Appointment (system): there are no free visit times to offer right now. Say that honestly and tell the caller " +
            "the team will call back with times. Do not invent a time.",
        ],
        actions: [],
      };
    }
    this.state = { ...this.state, phase: "offered", offered: slots };
    return {
      sections: [
        `Appointment (system): offer EXACTLY these visit times and ask the caller to pick one: ` +
          `${slots.map((s, i) => `${i + 1}) ${s.label}`).join(", ")}. These come from the calendar; never offer any other time.`,
      ],
      actions: [],
    };
  }

  /** Ordinal, digit or time-expression match against the offered slots. */
  private matchChoice(utterance: string, slots: VisitSlot[]): VisitSlot | null {
    if (!utterance.trim() || slots.length === 0) return null;
    const normalized = ` ${normalizeForMatching(utterance)} `;

    for (const ordinal of ORDINALS) {
      if (ordinal.index >= slots.length) continue;
      if (ordinal.words.some((word) => normalized.includes(` ${normalizeForMatching(word)} `) || normalized.includes(`${normalizeForMatching(word)} `))) {
        return slots[ordinal.index];
      }
    }

    const number = parseNumber(utterance);
    if (number && Number.isInteger(number.value) && number.value >= 1 && number.value <= slots.length) {
      return slots[number.value - 1];
    }

    // A restated time only counts when it clearly matches one offered label.
    const gloss = this.deps.pack.hasTime(utterance) ? normalizeForMatching(this.deps.pack.timeGloss(utterance)) : "";
    if (gloss) {
      const matches = slots.filter((slot) => {
        const label = normalizeForMatching(slot.label);
        return gloss.split(" ").filter((t) => t.length > 2).every((token) => label.includes(token));
      });
      if (matches.length === 1) return matches[0];
    }
    return null;
  }
}
